" ----------
" Vim Config
" ----------

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Colorschemes
Plugin 'Colour-Sampler-Pack'
Plugin 'ajmwagar/vim-deus'
Plugin 'altercation/vim-colors-solarized'
Plugin 'candycode.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'flazz/vim-colorschemes'
Plugin 'mhartington/oceanic-next'
Plugin 'molokai'
Plugin 'tpope/vim-vividchalk'
Plugin 'wgibbs/vim-irblack'

" ******************* Syntax Highlighting *******************
" Elixir
Plugin 'elixir-lang/vim-elixir'

" Clojure
Plugin 'guns/vim-clojure-static'

" CoffeeScript
Plugin 'kchmck/vim-coffee-script'

" Go
Plugin 'fatih/vim-go'

" JavaScript
Plugin 'chemzqm/vim-jsx-improve'
"Plugin 'peitalin/vim-jsx-typescript'
Plugin 'juvenn/mustache.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'peitalin/vim-jsx-typescript'
Plugin 'maxmellon/vim-jsx-pretty'
Plugin 'nono/vim-handlebars'
Plugin 'pangloss/vim-javascript'

" Jenkins
Plugin 'martinda/Jenkinsfile-vim-syntax'

" Python
Plugin 'Vimjas/vim-python-pep8-indent'

" Jinja2
Plugin 'Glench/Vim-Jinja2-Syntax'

" Ruby
Plugin 'tpope/vim-endwise'
Plugin 'vim-ruby/vim-ruby'

" Scala
Plugin 'rosstimson/scala-vim-support'

" General Editing
Plugin 'camelcasemotion'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'mattn/emmet-vim'

" Clipboard
Plugin 'ojroques/vim-oscyank'

" Searching
Plugin 'mileszs/ack.vim'
Plugin 'henrik/vim-qargs'
Plugin 'ctrlpvim/ctrlp.vim'

" Navigation
"Plugin 'tpope/vim-vinegar'
Plugin 'tpope/vim-eunuch'
Plugin 'scrooloose/nerdtree'

" Development Tool Integration
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

" let g:deoplete#enable_at_startup = 1

call vundle#end()

filetype plugin indent on

syntax on

runtime! init/**.vim

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
