" ----------
" Vim Config
" ----------

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Colorschemes
Plugin 'Colour-Sampler-Pack'
Plugin 'altercation/vim-colors-solarized'
Plugin 'candycode.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'flazz/vim-colorschemes'
Plugin 'mhartington/oceanic-next'
Plugin 'molokai'
Plugin 'tpope/vim-vividchalk'
Plugin 'wgibbs/vim-irblack'

" ******************* Syntax Highlighting *******************

" Elixir
Plugin 'elixir-lang/vim-elixir'

" Clojure
Plugin 'guns/vim-clojure-static'

" Go
Plugin 'fatih/vim-go'

" JavaScript
Plugin 'Shougo/denite.nvim'
Plugin 'Shougo/deoplete.nvim'
Plugin 'chemzqm/vim-jsx-improve'
Plugin 'dense-analysis/ale'
Plugin 'juvenn/mustache.vim'
Plugin 'HerringtonDarkholme/yats.vim'
Plugin 'leafgarland/typescript-vim'
" Plugin 'mhartington/nvim-typescript'
" Plugin 'Quramy/tsuquyomi'
Plugin 'mxw/vim-jsx'
Plugin 'nono/vim-handlebars'
Plugin 'pangloss/vim-javascript'

" Jinja2
Plugin 'hiphish/jinja.vim'

" Ruby
Plugin 'tpope/vim-endwise'
Plugin 'vim-ruby/vim-ruby'

" Scala
Plugin 'rosstimson/scala-vim-support'

" General Editing
Plugin 'camelcasemotion'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Searching
Plugin 'mileszs/ack.vim'
Plugin 'henrik/vim-qargs'
Plugin 'ctrlpvim/ctrlp.vim'

" Navigation
Plugin 'scrooloose/nerdtree'

" Development Tool Integration
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

" Enable deoplete at startup
" let g:deoplete#enable_at_startup = 1

call vundle#end()

filetype plugin indent on

syntax on

runtime! init/**.vim

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
